-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table comentario_model (
  id                            bigint generated by default as identity not null,
  texto_comentario              varchar(255),
  receta_id                     bigint,
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_comentario_model primary key (id)
);

create table descripcion_model (
  id                            bigint generated by default as identity not null,
  descripcion_texto             varchar(255),
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_descripcion_model primary key (id)
);

create table ingrediente_model (
  id                            bigint generated by default as identity not null,
  name_ingrediente              varchar(255),
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_ingrediente_model primary key (id)
);

create table receta_model (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  categoria                     varchar(255),
  dificultad                    varchar(255),
  descripcion_id                bigint,
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint uq_receta_model_descripcion_id unique (descripcion_id),
  constraint pk_receta_model primary key (id)
);

create table receta_model_ingrediente_model (
  receta_model_id               bigint not null,
  ingrediente_model_id          bigint not null,
  constraint pk_receta_model_ingrediente_model primary key (receta_model_id,ingrediente_model_id)
);

-- foreign keys and indices
create index ix_comentario_model_receta_id on comentario_model (receta_id);
alter table comentario_model add constraint fk_comentario_model_receta_id foreign key (receta_id) references receta_model (id) on delete restrict on update restrict;

alter table receta_model add constraint fk_receta_model_descripcion_id foreign key (descripcion_id) references descripcion_model (id) on delete restrict on update restrict;

create index ix_receta_model_ingrediente_model_receta_model on receta_model_ingrediente_model (receta_model_id);
alter table receta_model_ingrediente_model add constraint fk_receta_model_ingrediente_model_receta_model foreign key (receta_model_id) references receta_model (id) on delete restrict on update restrict;

create index ix_receta_model_ingrediente_model_ingrediente_model on receta_model_ingrediente_model (ingrediente_model_id);
alter table receta_model_ingrediente_model add constraint fk_receta_model_ingrediente_model_ingrediente_model foreign key (ingrediente_model_id) references ingrediente_model (id) on delete restrict on update restrict;


-- !Downs

-- drop all foreign keys
alter table comentario_model drop constraint if exists fk_comentario_model_receta_id;
drop index if exists ix_comentario_model_receta_id;

alter table receta_model drop constraint if exists fk_receta_model_descripcion_id;

alter table receta_model_ingrediente_model drop constraint if exists fk_receta_model_ingrediente_model_receta_model;
drop index if exists ix_receta_model_ingrediente_model_receta_model;

alter table receta_model_ingrediente_model drop constraint if exists fk_receta_model_ingrediente_model_ingrediente_model;
drop index if exists ix_receta_model_ingrediente_model_ingrediente_model;

-- drop all
drop table if exists comentario_model;

drop table if exists descripcion_model;

drop table if exists ingrediente_model;

drop table if exists receta_model;

drop table if exists receta_model_ingrediente_model;

